apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
data:
  username: <your_username_in_base64>
  password: <your_password_in_base64>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:<rabbitmq_version>
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: password
          ports:
            - containerPort: <rabbitmq_port>
            - containerPort: <rabbitmq_management_port>
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-amqp
      port: <rabbitmq_port>
      targetPort: <rabbitmq_port>
    - name: rabbitmq-management
      port: <rabbitmq_management_port>
      targetPort: <rabbitmq_management_port>
