version: '3'

services:
  keycloak:
    container_name: keycloak_container
    image: keycloak:<version_number>
    volumes:
      - keycloak_data:/opt/keycloak/conf/
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_MANAGEMENT_USER: ${KEYCLOAK_MANAGEMENT_USER}
      KEYCLOAK_MANAGEMENT_PASSWORD: ${KEYCLOAK_MANAGEMENT_PASSWORD}
      KEYCLOAK_DATABASE_HOST: ${POSTGRES_HOST}
      KEYCLOAK_DATABASE_PORT: ${POSTGRES_PORT}
      KEYCLOAK_DATABASE_NAME: ${POSTGRES_DB_NAME}
      KEYCLOAK_DATABASE_USER: ${POSTGRES_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}
    depends_on:
      - postgres
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

volumes:
  keycloak_data:
